[package]
name = "eclat"
version = "0.1.0"
edition = "2021"
authors = ["Makel", "@.makel"]
description = "Éclat — a high-performance, parallel Roblox asset upload engine."

[dependencies]
# --> [`runtime`]
tokio = { version = "1.38", features = ["full", "fs"] }

# --> [`http`]
# linux without libssl-dev: use default-features = false with rustls-tls instead.
reqwest = { version = "0.12", features = ["json", "multipart", "stream"] }

# --> [`serde`]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# --> [`bytes`]
hex = "0.4"
bytes = "1"
base64 = "0.22"

# --> [`server`]
axum = "0.7"

# --> [`color`]
colored = "2.1"
enable-ansi-support = "0.2"

[[bin]]
name = "eclat"
path = "src/main.rs"
